language: android
jdk:
  - oraclejdk8

sudo: required

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  - ${TRAVIS_BUILD_DIR}/gradle/caches/
  - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
  - ${TRAVIS_BUILD_DIR}/android-sdk/extras/

deploy:
  provider: releases
  api_key:
    secure: 331f1a0e692b7d50c4a308fdb1425107b52c2038
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true